### ISSUE TITLE
How can  I use my .jks ? 

### ISSUE THREAD

**Issue by HitoLiu10** [jeasoon-osp/Apk-Reinforce-Tool#1]
How can  I use my .jks ? 
I replaced “signer.jks、signer.properties” in "ReinforceTool\src\main\resources\apk\signer\" wiht my    .jks file,but it didn't work!
Thanks

**Comment by Jeasoon** [comment]
Are you sure that reinforcing apk result is success (exit code is 0)?

There are many logs as follow. At the end, you can find the log "sign apk file cmd: ..." when success. This is the sign command. 

Success:
![1557749865846](https://user-images.githubusercontent.com/17696727/57620718-32514880-75bc-11e9-9a44-41d23ff59e13.jpg)

Failed:
![image](https://user-images.githubusercontent.com/17696727/57621751-d805b700-75be-11e9-8342-2485ab36e4f4.png)

when signing apk, jks file will be copied to temporary directory. After signing, jks should be copied to temporary directory. You can follow the temporary jks file path and compare with your jks file.

I do a test in my computer, it worked.

**Comment by HitoLiu10** [comment]
I am sure that reinforcing apk result is success (exit code is 0)。The app is working on my phone.
I have find the temporary directory and 1.0.1.jks file.
Now I want to use my jks file ,but I don't know how to do.
When signing the apk, There are many parameters such as: key pass、key-alias...
How can I modify these parameters?
I don't konw where the 1.0.1.jks file in temporary dir from?

**Comment by Jeasoon** [comment]
You should change as follows:

* replace the key store `ReinforceTool/src/main/resources/apk/signer/signer.jks`
* modify sign parameter `ReinforceTool/src/main/resources/apk/signer/signer.properties`

signer.properties parameter:

* --ks: the jks file path, can be empty. if empty, use `ReinforceTool/src/main/resources/apk/signer/signer.jks`
* --ks-package: just a directory name for cache jks directory. You can change it to anything, but it should be a directory name
* --ks-version: just a version name for cache jks file, I suggest that when you update signer.properties, version name should be updated
* --ks-key-alias: key store alias that you specified when you created a key store
* --ks-pass: key store password that you specified when you created a key store
* --key-pass: key password that you specified when you created a key store

`ReinforceTool/src/main/resources/apk/signer/signer.jks` will be copied to `temporaryDir(depends on system)/ApkReinforceTool/signer/${ks-package}/${ks-version}.jks`

You can refer to `Apk-Reinforce-Tool/ReinforceTool/src/main/java/org/jeson/reinforcetool/processor/SignerProcessor.java` line 139.

You can refer to command `keytool(in jdk)` and `apksigner(in android sdk)` too

My english is poor, please forgive my bad expression

你能说中文吗?

**Comment by HitoLiu10** [comment]
可以正常工作了，我把temporary dir完全删除，在替换jks，并重新编译可以了。
非常感谢。
但是我在使用的过程中发现app不能是中文名称，否则会报错。

**Comment by Jeasoon** [comment]
你会说中文啊. 我用英语说得太不得劲了.

加固时, jks文件会放置到缓存目录中, 并用在`signer.properties`文件配置的包名和版本名作为标识. 程序运行过程中, 如果发现已经有了缓存就不再复制Jar包内的jks文件了. 这可能是你遇到问题的原因

其实签名这一块可以再优化的, 真正的项目内, 不应该把签名文件放到Jar里面, 需要独立出来. 因为这是一个练习项目, 也为了省事, 就暂时将它打包到Jar了. 以后有机会再优化吧.

这个项目只是我练习加固的项目, 没想到还真有人看到了. 程序里面还有很多优化的地方, 如果要在实际项目中使用, 建议你再修改、优化下

感谢关注
